name: Packer Workflow

on:
  push:
    branches:
      - assignment04

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Packer
      run: |
          curl -O https://releases.hashicorp.com/packer/${{ env.PACKER_VERSION }}/packer_${{ env.PACKER_VERSION }}_linux_amd64.zip
          unzip packer_${{ env.PACKER_VERSION }}_linux_amd64.zip
          sudo mv packer /usr/local/bin
      env:
        PACKER_VERSION: "1.10.0"

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Create .env file
      run: |
        echo "DB_USERNAME=${{ secrets.POSTGRES_USER }}" > packer_files/.env
        echo "DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> packer_files/.env
        echo "PORT=5432" >> packer_files/.env
        echo "WEB_SITE_PORT=3000" >> packer_files/.env
        echo "DB_DATABASE=${{ secrets.POSTGRES_DB }}" >> packer_files/.env

    - name: Create zip file
      run: zip -r webapp-fork-main.zip .
    
    - name: Move zip file to packer folder
      run: mv webapp-fork-main.zip packer_files/

    - name: Initialize Packer
      run: cd packer_files && packer init .

    - name: Format Packer Configuration
      run: cd packer_files && packer fmt .

    - name: Validate Packer Configuration
      run: cd packer_files && packer validate .

    - name: Build the Packer image
      run: cd packer_files && packer build image.pkr.hcl

