name: Compile Code
on:
  pull_request:
    branches:
      - assignment03

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install

      - name: Start PostgreSQL Service
        if: ${{ !contains(steps.status.outputs.service_status, 'running') }}
        run: sudo service postgresql start

      - name: Adjust Permissions on PostgreSQL Socket File
        run: sudo chmod 777 /var/run/postgresql/.s.PGSQL.5432 || true

      - name: Change PostgreSQL Password
        run: |
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '${{ secrets.POSTGRES_PASSWORD }}';"

      - name: Update PostgreSQL Authentication Method
        run: |
          sudo sed -i 's/^\(host.*all.*all.*\)\(ident\)\(.*\)$/\1md5\3/g' /var/lib/pgsql/data/pg_hba.conf

      - name: Restart PostgreSQL
        run: sudo systemctl restart postgresql

      - name: Create PostgreSQL Database
        run: |
          sudo -u postgres psql -c "CREATE DATABASE test01;"

      - name: Login to PostgreSQL
        run: |
          export PGPASSWORD='${{ secrets.POSTGRES_PASSWORD }}'
          psql -U postgres -h localhost -d postgres -c "SELECT version();"

      - name: Run Tests
        env:
          DB_USERNAME: ${{ secrets.POSTGRES_USER }}
          DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DB_DATABASE: ${{ secrets.POSTGRES_DB }}
          PORT: 5432
          WEB_SITE_PORT: 3000
        run: npm test
