name: Compile Code
on:
  pull_request:
    branches:
      - assignment03
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Password@12345
          POSTGRES_DB: test01
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        env:
          DB_USERNAME: postgres
          DB_PASSWORD: Password@12345
          PORT: 5432
          WEB_SITE_PORT: 3000
          DB_DATABASE: test01
        run: npm test
