name: Compile Code
on:
  pull_request:
    branches:
      - postgres
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install

      - name: Check PostgreSQL Version
        run: |
          psql --version

      - name: Run Tests
        run: npm test
