name: Compile Code
on:
  pull_request:
    branches:
      - assignment03

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install

      - name: Set up PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v5
        with:
          postgresql-version: '13'

      - name: Run Tests
        env:
          DB_USERNAME: ${{ secrets.POSTGRES_USER }}
          DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DB_DATABASE: ${{ secrets.POSTGRES_DB }}
          PORT: 5432
          WEB_SITE_PORT: 3000
        run: npm test
