name: Compile Code
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install
      
      - name: Set up PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v5
        with:
          postgresql-version: '13'

      - name: Confirm PostgreSQL connection
        run: |
          psql -U postgres -h localhost -d postgres -c "SELECT version();"

      - name: Run Tests
        run: npm test
